[package]
name = "godot-core"
description = "Core types and class registration for Godot 4 GDExtension (see the godot crate)."
version = "0.1.0"
build = "build.rs"
license = "MIT"
workspace = ".."
edition = "2021"
rust-version = "1.70"
publish = false

[features]
default = []
double-precision = ["godot-sys/double-precision"]

[dependencies]
godot-sys = { path = "../godot-sys", version = "0.1.0" }

[build-dependencies]
godot-codegen = { path = "../godot-codegen", version = "0.1.0" }
